[package]
name = "hyper-examples"
version = "0.1.0"
authors = ["The Tor Project, Inc.", "Ramid Khan <ramidzkh@gmail.com>", "Niel Duysters"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Examples demonstrating the usage of Arti with hyper"
publish = false

[dependencies]
anyhow = "1.0.97"
arti-client = { path = "../../crates/arti-client", features = ["onion-service-service"] }
bytes = "1.10.1"
futures = "0.3.14"
http = "1.3.1"
http-body-util = "0.1.0"
hyper = { version = "1.6", features = ["http1", "client", "server"] }
hyper-util = { version = "0.1.11", features = ["tokio", "client-legacy", "http1"] }
safelog = { path = "../../crates/safelog" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
tokio-native-tls = "0.3.1"
tokio-rustls = "0.26.2"
tokio-util = "0.7.10"
tor-cell = { path = "../../crates/tor-cell" }
tor-hsservice = { path = "../../crates/tor-hsservice" }
tor-proto = { path = "../../crates/tor-proto" }
tor-rtcompat = { path = "../../crates/tor-rtcompat" }
tower-service = "0.3.3"
tracing-subscriber = "0.3.3"
webpki-roots = "0.26.8"
