#!/usr/bin/env bash
set -xeuo pipefail

# Get chutney bin from env or PATH
CHUTNEY_BIN="${CHUTNEY_BIN:-$(type -P chutney)}"

export CHUTNEY_DATA_DIR="${CHUTNEY_DATA_DIR:-$(pwd)}"

if [ -z "${RUST_LOG:-}" ]; then
    echo "Setting RUST_LOG=info for your convenience."
    export RUST_LOG=info
fi

target="basic"
cd "$(git rev-parse --show-toplevel)"

./tests/chutney/setup

cargo run -p arti-bench --locked --release -- -c "${CHUTNEY_DATA_DIR}/nodes/arti.toml" "$@"

"${CHUTNEY_BIN}" stop "$target"
